In [1]:
import numpy as np

1. Решите линейную систему

In [2]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
np.linalg.solve(A, B)

array([-9.2       ,  0.9       ,  6.46666667])

2. Найдите псевдорешение:  
x + 2y – z = 1  
3x – 4y = 7  
8x – 5y + 2z = 12  
2x – 5z = 7  
11x + 4y – 7z = 15

In [16]:
A = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, -5, 0], [11, 4, -7]])
B = np.array([1, 7, 12, 7, 15])
np.linalg.lstsq(A, B, rcond=None)

(array([ 1.15601029, -0.889718  , -0.85029782]),
 array([0.66772534]),
 3,
 array([14.89650167, 10.4695886 ,  2.73531577]))

3. Сколько решений имеет линейная система.  
Если ноль – то измените вектор правой части так, чтобы система стала совместной, и решите ее. 

In [48]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[12, 2, 1]]) # 0 solusions
B = np.array([[7, 8, 9]])
C = np.concatenate((A, B.T), axis=1)
print(C)
print(np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001))
np.linalg.solve(A, B[0])

[[1 2 3 7]
 [4 5 6 8]
 [7 8 9 9]]
2 2


array([-14.33333333,  22.66666667,  -8.        ])

4. Вычислите LU-разложение матрицы.

5. Найдите нормальное псевдорешение недоопределенной системы:  
x + 2y – z = 1  
8x – 5y + 2z = 12  
Для этого определите функцию Q(x,y,z), равную норме решения, и найдите ее минимум. 

6. Найдите одно из псевдорешений вырожденной системы.  
Попробуйте также отыскать и нормальное псевдорешение.